apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: kube-scheduler-rs
    app.kubernetes.io/version: 0.1.0
  name: kube-scheduler-rs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: kube-scheduler-rs
    app.kubernetes.io/version: 0.1.0
  name: kube-scheduler-rs-service-account
  namespace: kube-scheduler-rs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-scheduler-rs
    app.kubernetes.io/version: 0.1.0
  name: kube-scheduler-rs-cluster-role
  namespace: kube-scheduler-rs
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/status
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes
      - namespaces
    verbs:
      - get
      - list
      - watch
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: kube-scheduler-rs
    app.kubernetes.io/version: 0.1.0
  name: kube-scheduler-rs
  namespace: kube-scheduler-rs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-scheduler-rs-cluster-role
subjects:
  - kind: ServiceAccount
    name: kube-scheduler-rs-service-account
    namespace: kube-scheduler-rs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: kube-scheduler-rs
    app.kubernetes.io/version: 0.1.0
  name: kube-scheduler-rs
  namespace: kube-scheduler-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-scheduler-rs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-scheduler-rs
        app.kubernetes.io/version: 0.1.0
    spec:
      containers:
        - command:
            - ./kube-scheduler-rs
          env:
            - name: ALGORITHM
              value: bin-packing
          image: ghcr.io/thomask33/kube-scheduler-rs:0.1.0
          name: kube-scheduler-rs
          # securityContext:
          #   allowPrivilegeEscalation: false
          #   capabilities:
          #     drop:
          #       - ALL
          #   readOnlyRootFilesystem: true
          #   runAsGroup: 12345
          #   runAsNonRoot: true
          #   runAsUser: 12345
          #   seccompProfile:
          #     type: RuntimeDefault
      serviceAccountName: kube-scheduler-rs-service-account
