name: docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

# make sure the pipeline is only running once
concurrency:
  group: docs-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --locked cargo-about
      - run: cargo about generate about.hbs > docs/license.md
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-roamlinks-plugin
      - run: mkdocs gh-deploy --force
